
package UI.SystemAdmin;

import UI.Requests.CreateRequest;
import UI.Requests.ViewRequestsJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;
import model.EcoSystem;
import model.UserAccount.UserAccount;


public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminworkArea
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount userAccount;
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
//        populateTree();
    }
    
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, EcoSystem ecosystem){
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.userAccount = userAccount;
        System.out.println(userAccount.getRole());
        if ("model.Role.AdminRole".equals(userAccount.getRole().getClass().getName())) {
        lblRequestTitle.setVisible(false);
        btnCreateRequest.setVisible(false);  
        lblEnterpriseTitle.setVisible(false);
        btnManageHospital.setVisible(false);
        btnManagePolice.setVisible(false);
        btnManageFire.setVisible(false);
        btnManageShelter.setVisible(false);
        lblUserAdminTitle.setVisible(false);
        btnUsers.setVisible(false);
        btnAdmins.setVisible(false);
        btnAreaAdmins.setVisible(false);
        lblRequestTitle.setVisible(true);
        btnCreateRequest.setVisible(true);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        lblRequestTitle = new javax.swing.JLabel();
        btnCreateRequest = new javax.swing.JButton();
        lblEnterpriseTitle = new javax.swing.JLabel();
        btnManageShelter = new javax.swing.JButton();
        btnManagePolice = new javax.swing.JButton();
        btnManageHospital = new javax.swing.JButton();
        btnManageFire = new javax.swing.JButton();
        lblUserAdminTitle = new javax.swing.JLabel();
        btnUsers = new javax.swing.JButton();
        btnAdmins = new javax.swing.JButton();
        btnAreaAdmins = new javax.swing.JButton();
        btnManageRequest = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome.setFont(new java.awt.Font("Lucida Grande", 3, 24)); // NOI18N
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText(" Campus Gaurdian ");
        add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 50, 900, -1));

        lblRequestTitle.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblRequestTitle.setText("Click to Create and manage specific Requests:");
        add(lblRequestTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        btnCreateRequest.setBackground(new java.awt.Color(255, 153, 153));
        btnCreateRequest.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnCreateRequest.setText("Create Requests");
        btnCreateRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateRequestActionPerformed(evt);
            }
        });
        add(btnCreateRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 160, 40));

        lblEnterpriseTitle.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblEnterpriseTitle.setText("Create Enterprises with use of below Buttons:");
        add(lblEnterpriseTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        btnManageShelter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Safe HOme.png"))); // NOI18N
        btnManageShelter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageShelterActionPerformed(evt);
            }
        });
        add(btnManageShelter, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 120, 100));

        btnManagePolice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Police.png"))); // NOI18N
        btnManagePolice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePoliceActionPerformed(evt);
            }
        });
        add(btnManagePolice, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 130, 100));

        btnManageHospital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/HOspital.jpg"))); // NOI18N
        btnManageHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageHospitalActionPerformed(evt);
            }
        });
        add(btnManageHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 100, 100));

        btnManageFire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fire.jpg"))); // NOI18N
        btnManageFire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFireActionPerformed(evt);
            }
        });
        add(btnManageFire, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 100, 100));

        lblUserAdminTitle.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblUserAdminTitle.setText("Create user and admins with use of below buttons:");
        add(lblUserAdminTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, -1, -1));

        btnUsers.setBackground(new java.awt.Color(255, 153, 153));
        btnUsers.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnUsers.setText("Users");
        btnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersActionPerformed(evt);
            }
        });
        add(btnUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 90, 30));

        btnAdmins.setBackground(new java.awt.Color(255, 153, 153));
        btnAdmins.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnAdmins.setText("Admin");
        btnAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminsActionPerformed(evt);
            }
        });
        add(btnAdmins, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 80, 30));

        btnAreaAdmins.setBackground(new java.awt.Color(255, 153, 153));
        btnAreaAdmins.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnAreaAdmins.setText("Area Admin");
        btnAreaAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaAdminsActionPerformed(evt);
            }
        });
        add(btnAreaAdmins, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, 120, 30));

        btnManageRequest.setBackground(new java.awt.Color(255, 153, 153));
        btnManageRequest.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnManageRequest.setText("Manage Requests");
        btnManageRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRequestActionPerformed(evt);
            }
        });
        add(btnManageRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 160, 40));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hospital");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 62, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Police");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 62, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Safe House");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 90, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Fire");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 62, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateRequestActionPerformed
        // TODO add your handling code here:
        CreateRequest createRequest = new CreateRequest(userProcessContainer, ecosystem);
        userProcessContainer.add("createRequest", createRequest);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateRequestActionPerformed

    private void btnManageShelterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageShelterActionPerformed
        // TODO add your handling code here:
        ManageShelterHomeJPanel manageShelter = new ManageShelterHomeJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("manageAdminJPanel", manageShelter);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageShelterActionPerformed

    private void btnManageFireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFireActionPerformed
        // TODO add your handling code here:
        ManageFireDept manageFire = new ManageFireDept(userProcessContainer, ecosystem);
        userProcessContainer.add("managePoliceDepartmentJPanel", manageFire);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageFireActionPerformed

    private void btnManagePoliceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePoliceActionPerformed
        // TODO add your handling code here:
        ManagePoliceDepartmentJPanel managePolice = new ManagePoliceDepartmentJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("managePoliceDepartmentJPanel", managePolice);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManagePoliceActionPerformed

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed
        // TODO add your handling code here:
        ManageUserJPanel manageUser = new ManageUserJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("manageUserJPanel", manageUser);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnUsersActionPerformed

    private void btnAdminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminsActionPerformed
        // TODO add your handling code here:
        ManageAdminJPanel manageAdmin = new ManageAdminJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("manageAdminJPanel", manageAdmin);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAdminsActionPerformed

    private void btnAreaAdminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaAdminsActionPerformed
        // TODO add your handling code here:
        ManageAreaJPanel manageArea = new ManageAreaJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("manageAdminJPanel", manageArea);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAreaAdminsActionPerformed

    private void btnManageRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRequestActionPerformed
        // TODO add your handling code here:
        ViewRequestsJPanel manageArea = new ViewRequestsJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("manageAdminJPanel", manageArea);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageRequestActionPerformed

    private void btnManageHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageHospitalActionPerformed
        // TODO add your handling code here:
        ManageHospitalDeptJPanel manageHospital = new ManageHospitalDeptJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("manageAdminJPanel", manageHospital);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageHospitalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmins;
    private javax.swing.JButton btnAreaAdmins;
    private javax.swing.JButton btnCreateRequest;
    private javax.swing.JButton btnManageFire;
    private javax.swing.JButton btnManageHospital;
    private javax.swing.JButton btnManagePolice;
    private javax.swing.JButton btnManageRequest;
    private javax.swing.JButton btnManageShelter;
    private javax.swing.JButton btnUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblEnterpriseTitle;
    private javax.swing.JLabel lblRequestTitle;
    private javax.swing.JLabel lblUserAdminTitle;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
